/* eslint-disable */
// NOTE This file was automatically generated. Do not edit directly.
import type { KeyAction, KeyRecord } from './types';

export const key = {
  '0':{"keyCode":39,"modKey":0} as KeyAction,
  '1':{"keyCode":30,"modKey":0} as KeyAction,
  '2':{"keyCode":31,"modKey":0} as KeyAction,
  '3':{"keyCode":32,"modKey":0} as KeyAction,
  '4':{"keyCode":33,"modKey":0} as KeyAction,
  '5':{"keyCode":34,"modKey":0} as KeyAction,
  '6':{"keyCode":35,"modKey":0} as KeyAction,
  '7':{"keyCode":36,"modKey":0} as KeyAction,
  '8':{"keyCode":37,"modKey":0} as KeyAction,
  '9':{"keyCode":38,"modKey":0} as KeyAction,
  'NULL':{"keyCode":0,"modKey":0} as KeyAction,
  'A':{"keyCode":4,"modKey":0} as KeyAction,
  'B':{"keyCode":5,"modKey":0} as KeyAction,
  'C':{"keyCode":6,"modKey":0} as KeyAction,
  'D':{"keyCode":7,"modKey":0} as KeyAction,
  'E':{"keyCode":8,"modKey":0} as KeyAction,
  'F':{"keyCode":9,"modKey":0} as KeyAction,
  'G':{"keyCode":10,"modKey":0} as KeyAction,
  'H':{"keyCode":11,"modKey":0} as KeyAction,
  'I':{"keyCode":12,"modKey":0} as KeyAction,
  'J':{"keyCode":13,"modKey":0} as KeyAction,
  'K':{"keyCode":14,"modKey":0} as KeyAction,
  'L':{"keyCode":15,"modKey":0} as KeyAction,
  'M':{"keyCode":16,"modKey":0} as KeyAction,
  'N':{"keyCode":17,"modKey":0} as KeyAction,
  'O':{"keyCode":18,"modKey":0} as KeyAction,
  'P':{"keyCode":19,"modKey":0} as KeyAction,
  'Q':{"keyCode":20,"modKey":0} as KeyAction,
  'R':{"keyCode":21,"modKey":0} as KeyAction,
  'S':{"keyCode":22,"modKey":0} as KeyAction,
  'T':{"keyCode":23,"modKey":0} as KeyAction,
  'U':{"keyCode":24,"modKey":0} as KeyAction,
  'V':{"keyCode":25,"modKey":0} as KeyAction,
  'W':{"keyCode":26,"modKey":0} as KeyAction,
  'X':{"keyCode":27,"modKey":0} as KeyAction,
  'Y':{"keyCode":28,"modKey":0} as KeyAction,
  'Z':{"keyCode":29,"modKey":0} as KeyAction,
  'Excl':{"keyCode":30,"modKey":2} as KeyAction,
  'At':{"keyCode":31,"modKey":2} as KeyAction,
  'Hash':{"keyCode":32,"modKey":2} as KeyAction,
  'Dol':{"keyCode":33,"modKey":2} as KeyAction,
  'Per':{"keyCode":34,"modKey":2} as KeyAction,
  'Caret':{"keyCode":35,"modKey":2} as KeyAction,
  'Amp':{"keyCode":36,"modKey":2} as KeyAction,
  'Aster':{"keyCode":37,"modKey":2} as KeyAction,
  'LPar':{"keyCode":38,"modKey":2} as KeyAction,
  'RPar':{"keyCode":39,"modKey":2} as KeyAction,
  'Enter':{"keyCode":40,"modKey":0} as KeyAction,
  'Esc':{"keyCode":41,"modKey":0} as KeyAction,
  'BkSpc':{"keyCode":42,"modKey":0} as KeyAction,
  'Tab':{"keyCode":43,"modKey":0} as KeyAction,
  'Space':{"keyCode":44,"modKey":0} as KeyAction,
  'Minus':{"keyCode":45,"modKey":0} as KeyAction,
  'Equal':{"keyCode":46,"modKey":0} as KeyAction,
  'LBra':{"keyCode":47,"modKey":0} as KeyAction,
  'LCBra':{"keyCode":47,"modKey":2} as KeyAction,
  'RBra':{"keyCode":48,"modKey":0} as KeyAction,
  'RCBra':{"keyCode":48,"modKey":2} as KeyAction,
  'BkSla':{"keyCode":49,"modKey":0} as KeyAction,
  'Pipe':{"keyCode":49,"modKey":2} as KeyAction,
  'Semi':{"keyCode":51,"modKey":0} as KeyAction,
  'Colon':{"keyCode":51,"modKey":2} as KeyAction,
  'Quote':{"keyCode":52,"modKey":0} as KeyAction,
  'DQ':{"keyCode":52,"modKey":2} as KeyAction,
  'Grave':{"keyCode":53,"modKey":0} as KeyAction,
  'Tilde':{"keyCode":53,"modKey":2} as KeyAction,
  'Comma':{"keyCode":54,"modKey":0} as KeyAction,
  'LT':{"keyCode":54,"modKey":2} as KeyAction,
  'Dot':{"keyCode":55,"modKey":0} as KeyAction,
  'RT':{"keyCode":55,"modKey":2} as KeyAction,
  'Slash':{"keyCode":56,"modKey":0} as KeyAction,
  'Que':{"keyCode":56,"modKey":2} as KeyAction,
  'Caps':{"keyCode":57,"modKey":0} as KeyAction,
  'F1':{"keyCode":58,"modKey":0} as KeyAction,
  'F2':{"keyCode":59,"modKey":0} as KeyAction,
  'F3':{"keyCode":60,"modKey":0} as KeyAction,
  'F4':{"keyCode":61,"modKey":0} as KeyAction,
  'F5':{"keyCode":62,"modKey":0} as KeyAction,
  'F6':{"keyCode":63,"modKey":0} as KeyAction,
  'F7':{"keyCode":64,"modKey":0} as KeyAction,
  'F8':{"keyCode":65,"modKey":0} as KeyAction,
  'F9':{"keyCode":66,"modKey":0} as KeyAction,
  'F10':{"keyCode":67,"modKey":0} as KeyAction,
  'F11':{"keyCode":68,"modKey":0} as KeyAction,
  'F12':{"keyCode":69,"modKey":0} as KeyAction,
  'PrSc':{"keyCode":70,"modKey":0} as KeyAction,
  'ScLk':{"keyCode":71,"modKey":0} as KeyAction,
  'Pause':{"keyCode":72,"modKey":0} as KeyAction,
  'Ins':{"keyCode":73,"modKey":0} as KeyAction,
  'Home':{"keyCode":74,"modKey":0} as KeyAction,
  'PgUp':{"keyCode":75,"modKey":0} as KeyAction,
  'Del':{"keyCode":76,"modKey":0} as KeyAction,
  'End':{"keyCode":77,"modKey":0} as KeyAction,
  'PgDn':{"keyCode":78,"modKey":0} as KeyAction,
  'Right':{"keyCode":79,"modKey":0} as KeyAction,
  'Left':{"keyCode":80,"modKey":0} as KeyAction,
  'Down':{"keyCode":81,"modKey":0} as KeyAction,
  'Up':{"keyCode":82,"modKey":0} as KeyAction,
  'NumLk':{"keyCode":83,"modKey":0} as KeyAction,
  'PadSlash':{"keyCode":84,"modKey":0} as KeyAction,
  'PadAster':{"keyCode":85,"modKey":0} as KeyAction,
  'PadMinus':{"keyCode":86,"modKey":0} as KeyAction,
  'PadPlus':{"keyCode":87,"modKey":0} as KeyAction,
  'PadEnter':{"keyCode":88,"modKey":0} as KeyAction,
  'Pad1':{"keyCode":89,"modKey":0} as KeyAction,
  'PadEnd':{"keyCode":89,"modKey":2} as KeyAction,
  'Pad2':{"keyCode":90,"modKey":0} as KeyAction,
  'PadDown':{"keyCode":90,"modKey":2} as KeyAction,
  'Pad3':{"keyCode":91,"modKey":0} as KeyAction,
  'PadPgDn':{"keyCode":91,"modKey":2} as KeyAction,
  'Pad4':{"keyCode":92,"modKey":0} as KeyAction,
  'PadLeft':{"keyCode":92,"modKey":2} as KeyAction,
  'Pad5':{"keyCode":93,"modKey":0} as KeyAction,
  'Pad6':{"keyCode":94,"modKey":0} as KeyAction,
  'PadRight':{"keyCode":94,"modKey":2} as KeyAction,
  'Pad7':{"keyCode":95,"modKey":0} as KeyAction,
  'PadHome':{"keyCode":95,"modKey":2} as KeyAction,
  'Pad8':{"keyCode":96,"modKey":0} as KeyAction,
  'PadUp':{"keyCode":96,"modKey":2} as KeyAction,
  'Pad9':{"keyCode":97,"modKey":0} as KeyAction,
  'PadPgUp':{"keyCode":97,"modKey":2} as KeyAction,
  'Pad0':{"keyCode":98,"modKey":0} as KeyAction,
  'PadIns':{"keyCode":98,"modKey":2} as KeyAction,
  'PadDot':{"keyCode":99,"modKey":0} as KeyAction,
  'PadDel':{"keyCode":99,"modKey":2} as KeyAction,
  'App':{"keyCode":101,"modKey":0} as KeyAction,
  'Power':{"keyCode":102,"modKey":0} as KeyAction,
  'PadEqual':{"keyCode":103,"modKey":0} as KeyAction,
  'F13':{"keyCode":104,"modKey":0} as KeyAction,
  'F14':{"keyCode":105,"modKey":0} as KeyAction,
  'F15':{"keyCode":106,"modKey":0} as KeyAction,
  'F16':{"keyCode":107,"modKey":0} as KeyAction,
  'F17':{"keyCode":108,"modKey":0} as KeyAction,
  'F18':{"keyCode":109,"modKey":0} as KeyAction,
  'F19':{"keyCode":110,"modKey":0} as KeyAction,
  'F20':{"keyCode":111,"modKey":0} as KeyAction,
  'F21':{"keyCode":112,"modKey":0} as KeyAction,
  'F22':{"keyCode":113,"modKey":0} as KeyAction,
  'F23':{"keyCode":114,"modKey":0} as KeyAction,
  'F24':{"keyCode":115,"modKey":0} as KeyAction,
  'LCtrl':{"keyCode":224,"modKey":0} as KeyAction,
  'LShift':{"keyCode":225,"modKey":0} as KeyAction,
  'LAlt':{"keyCode":226,"modKey":0} as KeyAction,
  'LGui':{"keyCode":227,"modKey":0} as KeyAction,
  'RCtrl':{"keyCode":228,"modKey":0} as KeyAction,
  'RShift':{"keyCode":229,"modKey":0} as KeyAction,
  'RAlt':{"keyCode":230,"modKey":0} as KeyAction,
  'RGui':{"keyCode":231,"modKey":0} as KeyAction,
} as const;
export const dict: KeyRecord = {
  "0": {"keyCode": 39, "modKey": 0},
  "1": {"keyCode": 30, "modKey": 0},
  "2": {"keyCode": 31, "modKey": 0},
  "3": {"keyCode": 32, "modKey": 0},
  "4": {"keyCode": 33, "modKey": 0},
  "5": {"keyCode": 34, "modKey": 0},
  "6": {"keyCode": 35, "modKey": 0},
  "7": {"keyCode": 36, "modKey": 0},
  "8": {"keyCode": 37, "modKey": 0},
  "9": {"keyCode": 38, "modKey": 0},
  "a": {"keyCode": 4, "modKey": 0},
  "A": {"keyCode": 4, "modKey": 2},
  "b": {"keyCode": 5, "modKey": 0},
  "B": {"keyCode": 5, "modKey": 2},
  "c": {"keyCode": 6, "modKey": 0},
  "C": {"keyCode": 6, "modKey": 2},
  "d": {"keyCode": 7, "modKey": 0},
  "D": {"keyCode": 7, "modKey": 2},
  "e": {"keyCode": 8, "modKey": 0},
  "E": {"keyCode": 8, "modKey": 2},
  "f": {"keyCode": 9, "modKey": 0},
  "F": {"keyCode": 9, "modKey": 2},
  "g": {"keyCode": 10, "modKey": 0},
  "G": {"keyCode": 10, "modKey": 2},
  "h": {"keyCode": 11, "modKey": 0},
  "H": {"keyCode": 11, "modKey": 2},
  "i": {"keyCode": 12, "modKey": 0},
  "I": {"keyCode": 12, "modKey": 2},
  "j": {"keyCode": 13, "modKey": 0},
  "J": {"keyCode": 13, "modKey": 2},
  "k": {"keyCode": 14, "modKey": 0},
  "K": {"keyCode": 14, "modKey": 2},
  "l": {"keyCode": 15, "modKey": 0},
  "L": {"keyCode": 15, "modKey": 2},
  "m": {"keyCode": 16, "modKey": 0},
  "M": {"keyCode": 16, "modKey": 2},
  "n": {"keyCode": 17, "modKey": 0},
  "N": {"keyCode": 17, "modKey": 2},
  "o": {"keyCode": 18, "modKey": 0},
  "O": {"keyCode": 18, "modKey": 2},
  "p": {"keyCode": 19, "modKey": 0},
  "P": {"keyCode": 19, "modKey": 2},
  "q": {"keyCode": 20, "modKey": 0},
  "Q": {"keyCode": 20, "modKey": 2},
  "r": {"keyCode": 21, "modKey": 0},
  "R": {"keyCode": 21, "modKey": 2},
  "s": {"keyCode": 22, "modKey": 0},
  "S": {"keyCode": 22, "modKey": 2},
  "t": {"keyCode": 23, "modKey": 0},
  "T": {"keyCode": 23, "modKey": 2},
  "u": {"keyCode": 24, "modKey": 0},
  "U": {"keyCode": 24, "modKey": 2},
  "v": {"keyCode": 25, "modKey": 0},
  "V": {"keyCode": 25, "modKey": 2},
  "w": {"keyCode": 26, "modKey": 0},
  "W": {"keyCode": 26, "modKey": 2},
  "x": {"keyCode": 27, "modKey": 0},
  "X": {"keyCode": 27, "modKey": 2},
  "y": {"keyCode": 28, "modKey": 0},
  "Y": {"keyCode": 28, "modKey": 2},
  "z": {"keyCode": 29, "modKey": 0},
  "Z": {"keyCode": 29, "modKey": 2},
  "!": {"keyCode": 30, "modKey": 2},
  "@": {"keyCode": 31, "modKey": 2},
  "#": {"keyCode": 32, "modKey": 2},
  "$": {"keyCode": 33, "modKey": 2},
  "%": {"keyCode": 34, "modKey": 2},
  "^": {"keyCode": 35, "modKey": 2},
  "&": {"keyCode": 36, "modKey": 2},
  "*": {"keyCode": 37, "modKey": 2},
  "(": {"keyCode": 38, "modKey": 2},
  ")": {"keyCode": 39, "modKey": 2},
  "\n": {"keyCode": 40, "modKey": 0},
  "\t": {"keyCode": 43, "modKey": 0},
  " ": {"keyCode": 44, "modKey": 0},
  "-": {"keyCode": 45, "modKey": 0},
  "_": {"keyCode": 45, "modKey": 2},
  "=": {"keyCode": 46, "modKey": 0},
  "+": {"keyCode": 46, "modKey": 2},
  "[": {"keyCode": 47, "modKey": 0},
  "{": {"keyCode": 47, "modKey": 2},
  "]": {"keyCode": 48, "modKey": 0},
  "}": {"keyCode": 48, "modKey": 2},
  "\\": {"keyCode": 49, "modKey": 0},
  "|": {"keyCode": 49, "modKey": 2},
  ";": {"keyCode": 51, "modKey": 0},
  ":": {"keyCode": 51, "modKey": 2},
  "'": {"keyCode": 52, "modKey": 0},
  "\"": {"keyCode": 52, "modKey": 2},
  "`": {"keyCode": 53, "modKey": 0},
  "~": {"keyCode": 53, "modKey": 2},
  ",": {"keyCode": 54, "modKey": 0},
  "<": {"keyCode": 54, "modKey": 2},
  ".": {"keyCode": 55, "modKey": 0},
  ">": {"keyCode": 55, "modKey": 2},
  "/": {"keyCode": 56, "modKey": 0},
  "?": {"keyCode": 56, "modKey": 2}
};
